runtime: nodejs18

instance_class: F2

env_variables:
  DEBUG: "*,-follow-redirects -express:* -body-parser:*"
  emailSender: "ohad.ohad"
  smtpServer: "smtp.gmail.com"
  smtpPort: "587"
  emailServerUser: "oha*****@gmail.com"
  emailServerPass: "*********"

handlers:
  - url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico